# 02_functions.R

#function for re-naming countries 
standardize_country_name <- function(country_name) {
  country_name <- ifelse(country_name == "Antigua and Barb.", "Antigua and Barbuda", country_name)
  country_name <- ifelse(country_name == "Bahamas, The", "Bahamas", country_name)
  country_name <- ifelse(country_name == "The Bahamas", "Bahamas", country_name)
  country_name <- ifelse(country_name == "Bolivia", "Bolivia (Plurinational State of)", country_name)
  country_name <- ifelse(country_name == "Bosnia", "Bosnia and Herzegovina", country_name)
  country_name <- ifelse(country_name == "British US Virgin Islands", "British Virgin Islands", country_name)
  country_name <- ifelse(country_name == "Brunei Darussalam", "Brunei", country_name)
  country_name <- ifelse(country_name == "Cape Verde", "Cabo Verde", country_name)
  country_name <- ifelse(country_name == "People's Republic of China", "China", country_name)
  country_name <- ifelse(country_name == "Congo (Kinshasa)", "Democratic Republic of the Congo", country_name)
  country_name <- ifelse(country_name == "Congo (Kinchasa)", "Democratic Republic of the Congo", country_name)
  country_name <- ifelse(country_name == "Congo, Dem. Rep.", "Democratic Republic of the Congo", country_name)
  country_name <- ifelse(country_name == "Democratic Republic of Congo", "Democratic Republic of the Congo", country_name)
  country_name <- ifelse(country_name == "Congo, Rep.", "Congo", country_name)
  country_name <- ifelse(country_name == "Congo (Brazzaville)", "Congo", country_name)
  country_name <- ifelse(country_name == "Republic of The Congo (Brazzaville)", "Congo", country_name)
  country_name <- ifelse(country_name == "Republic of the Congo", "Congo", country_name)
  country_name <- ifelse(country_name == "Republic of Congo", "Congo", country_name)
  country_name <- ifelse(country_name == "Côte d'Ivoire", "Côte D'Ivoire", country_name)
  country_name <- ifelse(country_name == "Cote d'Ivoire", "Côte D'Ivoire", country_name)
  country_name <- ifelse(country_name == "Cote D'Ivoire", "Côte D'Ivoire", country_name)
  country_name <- ifelse(country_name == "Ivory Coast", "Côte D'Ivoire", country_name)
  country_name <- ifelse(country_name == "Curacao", "Curaçao", country_name)
  country_name <- ifelse(country_name == "Cura?ao", "Curaçao", country_name)
  country_name <- ifelse(country_name == "Czech Republic", "Czechia", country_name)
  country_name <- ifelse(country_name == "North Korea", "Democratic People's Republic of Korea", country_name)
  country_name <- ifelse(country_name == "East Timor", "Timor-Leste", country_name)
  country_name <- ifelse(country_name == "Egypt, Arab Rep.", "Egypt", country_name)
  country_name <- ifelse(country_name == "Eswatini", "Swaziland", country_name)
  country_name <- ifelse(country_name == "Kingdom of Eswatini", "Swaziland", country_name)
  country_name <- ifelse(country_name == "Federated States of Micronesia", "Micronesia (Federated States of)", country_name)
  country_name <- ifelse(country_name == "Micronesia, Fed. Sts.", "Micronesia (Federated States of)", country_name)
  country_name <- ifelse(country_name == "Micronesia Federated States of", "Micronesia (Federated States of)", country_name)
  country_name <- ifelse(country_name == "Gambia", "Gambia (Republic of The)", country_name)
  country_name <- ifelse(country_name == "Gambia, The", "Gambia (Republic of The)", country_name)
  country_name <- ifelse(country_name == "The Gambia", "Gambia (Republic of The)", country_name)
  country_name <- ifelse(country_name == "Hong Kong SAR, China", "Hong Kong", country_name)
  country_name <- ifelse(country_name == "Hong Kong SAR PRC", "Hong Kong", country_name)
  country_name <- ifelse(country_name == "Iran", "Iran (Islamic Republic of)", country_name)
  country_name <- ifelse(country_name == "Iran Islamic Republic of", "Iran (Islamic Republic of)", country_name)
  country_name <- ifelse(country_name == "Iran, Islamic Rep.", "Iran (Islamic Republic of)", country_name)
  country_name <- ifelse(country_name == "Korea, Dem. People's Rep.", "Democratic People's Republic of Korea", country_name)
  country_name <- ifelse(country_name == "Korea, Rep.", "Republic of Korea", country_name)
  country_name <- ifelse(country_name == "Korea Republic of", "Republic of Korea", country_name)
  country_name <- ifelse(country_name == "Korea", "Republic of Korea", country_name)
  country_name <- ifelse(country_name == "South Korea", "Republic of Korea", country_name)
  country_name <- ifelse(country_name == "Kyrgyz Republic", "Kyrgyzstan", country_name)
  country_name <- ifelse(country_name == "Lao People's Democratic Republic", "Laos", country_name)
  country_name <- ifelse(country_name == "Lao PDR", "Laos", country_name)
  country_name <- ifelse(country_name == "Lao Peoples Dem. Republic", "Laos", country_name)
  country_name <- ifelse(country_name == "Macedonia, North", "North Macedonia", country_name)
  country_name <- ifelse(country_name == "Macedonia", "North Macedonia", country_name)
  country_name <- ifelse(country_name == "Macedonia former Yugoslav Republic (1993-)", "North Macedonia", country_name)
  country_name <- ifelse(country_name == "Republic of Macedonia", "North Macedonia", country_name)
  country_name <- ifelse(country_name == "Moldova", "Republic of Moldova", country_name)
  country_name <- ifelse(country_name == "Moldova Republic of", "Republic of Moldova", country_name)
  country_name <- ifelse(country_name == "Myanmar (Burma)", "Myanmar", country_name)
  country_name <- ifelse(country_name == "Burma/Myanmar", "Myanmar", country_name)
  country_name <- ifelse(country_name == "Netherlands", "Netherlands (Kingdom of the)", country_name)
  country_name <- ifelse(country_name == "the Netherlands", "Netherlands (Kingdom of the)", country_name)
  country_name <- ifelse(country_name == "The Netherlands", "Netherlands (Kingdom of the)", country_name)
  country_name <- ifelse(country_name == "Pakistan", "Pakistan", country_name)
  country_name <- ifelse(country_name == "Palestine", "State of Palestine", country_name)
  country_name <- ifelse(country_name == "West Bank and Gaza", "State of Palestine", country_name)
  country_name <- ifelse(country_name == "Republic of Moldova", "Moldova", country_name)
  country_name <- ifelse(country_name == "Romania", "Romania", country_name)
  country_name <- ifelse(country_name == "Russia", "Russian Federation", country_name)
  country_name <- ifelse(country_name == "S. Sudan", "South Sudan", country_name)
  country_name <- ifelse(country_name == "Saint Kitts and Nevis", "St. Kitts and Nevis", country_name)
  country_name <- ifelse(country_name == "Saint Lucia", "St. Lucia", country_name)
  country_name <- ifelse(country_name == "Saint Martin (Dutch)", "Sint Maarten", country_name)
  country_name <- ifelse(country_name == "Sint Maarten (Dutch part)", "Sint Maarten", country_name)
  country_name <- ifelse(country_name == "Saint Vincent and the Grenadines", "St. Vincent and the Grenadines", country_name)
  country_name <- ifelse(country_name == "Saint Vincent and The Grenadines", "St. Vincent and the Grenadines", country_name)
  country_name <- ifelse(country_name == "Slovak Republic", "Slovakia", country_name)
  country_name <- ifelse(country_name == "São Tomé and Príncipe", "Sao Tome and Principe", country_name)
  country_name <- ifelse(country_name == "Syria", "Syrian Arab Republic", country_name)
  country_name <- ifelse(country_name == "Taiwan", "Taiwan (Province of China)", country_name)
  country_name <- ifelse(country_name == "Taiwan, China", "Taiwan (Province of China)", country_name)
  country_name <- ifelse(country_name == "Taiwan ROC", "Taiwan (Province of China)", country_name)
  country_name <- ifelse(country_name == "Tanzania", "United Republic of Tanzania", country_name)
  country_name <- ifelse(country_name == "Tanzania United Republic of", "United Republic of Tanzania", country_name)
  country_name <- ifelse(country_name == "Türkiye", "Turkey", country_name)
  country_name <- ifelse(country_name == "Turkiye", "Turkey", country_name)
  country_name <- ifelse(country_name == "Turkey", "Türkiye", country_name)
  country_name <- ifelse(country_name == "United Kingdom", "United Kingdom of Great Britain and Northern Ireland", country_name)
  country_name <- ifelse(country_name == "UK", "United Kingdom of Great Britain and Northern Ireland", country_name)
  country_name <- ifelse(country_name == "United Republic of Tanzania", "Tanzania", country_name)
  country_name <- ifelse(country_name == "United States", "United States of America", country_name)
  country_name <- ifelse(country_name == "United States Virgin Islands", "Virgin Islands, U.S.", country_name)
  country_name <- ifelse(country_name == "US Virgin Islands", "Virgin Islands, U.S.", country_name)
  country_name <- ifelse(country_name == "UAE", "United Arab Emirates", country_name)
  country_name <- ifelse(country_name == "Venezuela", "Venezuela, Bolivarian Republic of", country_name)
  country_name <- ifelse(country_name == "Venezuela, RB", "Venezuela, Bolivarian Republic of", country_name)
  country_name <- ifelse(country_name == "Virgin Islands (U.S.)", "Virgin Islands, U.S.", country_name)
  country_name <- ifelse(country_name == "Vietnam", "Viet Nam", country_name)
  country_name <- ifelse(country_name == "Yemen, Rep.", "Yemen", country_name)
  country_name <- ifelse(country_name == "Republic of Yemen", "Yemen", country_name)
  country_name <- ifelse(country_name == "U.S.A", "United States of America", country_name)
  country_name <- ifelse(country_name == "USA", "United States of America", country_name)
  
  
  # Remove any text in parentheses (with surrounding whitespace)
  country_name <- gsub("\\s*\\(.*?\\)", "", country_name, fixed = TRUE)
  
  # Change "&" to "and"
  country_name <- gsub("&", "and", country_name, fixed = TRUE)
  
  # Trim whitespace
  trimws(country_name)
}

